### ISSUE TITLE
Error: undefined is not an object( evaluating 'SongsCollection.getAll')

### ISSUE THREAD

**Issue by sseengal** [cinder92/react-native-get-music-files#6] opened 2017-08-05 07:47 UTC
Hi, trying to figure out what this error means

**Comment by flarocca** [comment] 2017-08-10 21:34
Hi, have you had some news related to this issue?
I'm facing the same problem.

**Comment by cinder92** [comment] 2017-08-15 16:56
Hello, sorry for delay, could you please tell me more about this error?

- Did you make `react-native link`
- Are you testing in real device?
- Are you testing in Android?

for now, this plugin only works on Android.

**Comment by flarocca** [comment] 2017-08-15 17:01
@cinder92 Thanks for answering.

In all of those cases the answer is "Yes". I haven't had enough time to dive into yet so I can't even suppose why nor what is causing the issue. 

Would you like me to send you some more info about some file or env?

Again, thanks for replying.

**Comment by cinder92** [comment] 2017-08-15 19:38
i will make an example asap, keep connected.

**Comment by flarocca** [comment] 2017-08-22 03:15
Hey, I think I figuredout where the problem is.

SongsCollection.java Line 138, BitmapFactory.decodeByteArray is returning null when the image does not exist.

I think you should check whether `songImage` is null or not.

```
Bitmap songImage = BitmapFactory.decodeByteArray(art, 0, art.length);

if(songImage != null){
    //...
}
```

Would you like me to make a PR?

**Comment by casual-coder-25** [comment] 2017-09-07 18:51
@flarocca did you fixed it. because i am facing this issue and i added that condition and still i am getting the same issue.

**Comment by flarocca** [comment] 2017-09-07 18:59
@baalu06 Yes, but there might be another issue:

`setDatasource` fails if the file it is trying to read is **unreadable** so the path is correct, the file exists, but it cannot be opened. 

Take at look at [one question I posted on StackOverflow](https://stackoverflow.com/questions/46029813/mediametadataretriever-setdatasourcenative-method-causes-runtimeexception-sta) that I've answered by myself.

The idea is to **wrap everything** inside the `while` into `try/catch` so if `setDatasource` fails accessing one file it can continue with the rest.

I would make a PR but the owner has never answered me about that.

**Comment by casual-coder-25** [comment] 2017-09-07 19:23
@flarocca many thanks for quick reply. I will check that in stack. you can create separate branch, many struggle in this point.

**Comment by flarocca** [comment] 2017-09-07 19:30
@baalu06 Ok, Let me know if it works and I will create and push a new branch with those corrections.

**Comment by casual-coder-25** [comment] 2017-09-07 19:31
@flarocca yes sure.

**Comment by casual-coder-25** [comment] 2017-09-07 19:40
@flarocca how you debugged that java file from react native?

**Comment by flarocca** [comment] 2017-09-07 19:44
@baalu06, I think you can't. What I did was to create a new project using Android Studio and test it there.

**Comment by casual-coder-25** [comment] 2017-09-07 19:47
oh ok thanks and there is already do while there still do we need to change it to while?

**Comment by flarocca** [comment] 2017-09-07 20:01
@baalu06 No, just add a `try/catch` inside.

```
do{
  try{

  } catch (Exception ex) {

  }
} while (...)
```

**Comment by flarocca** [comment] 2017-09-07 20:42
@baalu06 By the way, Vote my question and answer up (in StackOverflow) please!!! Thanks!!!

**Comment by casual-coder-25** [comment] 2017-09-08 20:12
@flarocca ha ha done. btw I didnt get any issue now and swell didnt get any result.:(

**Comment by flarocca** [comment] 2017-09-08 20:18
@baalu06 Are you using a real device or an emulator? Have you tried with a isolated Android Studio project? Have you set permissions in manifest?

```
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.STORAGE" />
```

in `android/app/src/main/AndroidManifest.xml`

**Comment by casual-coder-25** [comment] 2017-09-08 20:33
@flarocca i will try with last line also.

**Comment by cinder92** [comment] 2017-09-09 02:50
hey y'all PR are very welcome, sorry for delay.

**Comment by cinder92** [comment] 2017-09-12 05:40
Remember that in Android 6 , 7 an so on, you need to ask permissions in order to read and write external storage, this plugin WRITE and READ external and internal storage. i recommend, `https://github.com/lucasferreira/react-native-android-permissions`

**Comment by Madhukanth** [comment] 2017-11-27 11:54
I am getting this error.

Null Pointer Exception when trying to compress Bitmap

Please help me to solve this

**Comment by flarocca** [comment] 2017-11-27 12:16
Just check that image is not null.
I will fork and send a PR as soon as I get some free time.

**Comment by Madhukanth** [comment] 2017-11-27 12:21
I think the image is null. 
I have music files with no images...

And thank you for your reply....

**Comment by Madhukanth** [comment] 2017-11-27 12:43
This is my actual error.

In the console window,

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference

I am using physical device do run.

i just added these code in the AndroidManifest.xml

<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.STORAGE" />

I also dont know whether I have permissions to access local storage.

**Comment by flarocca** [comment] 2017-11-27 13:13
@Madhukanth that error is thrown because of the null image reference.

**Comment by Madhukanth** [comment] 2017-11-27 13:50
How could I handle that exception???
Is there any way to do it??
Please tell me...

**Comment by flarocca** [comment] 2017-11-27 14:00
https://github.com/cinder92/react-native-get-music-files/blob/master/android/src/main/java/com/dantecervantes/react/SongsCollection.java, Line 138.

Add a null-check for the image, take a look at my previous comments on this thread

**Comment by Madhukanth** [comment] 2017-11-27 14:02
Ok thank you so much.
I will take a look at it.

**Comment by Madhukanth** [comment] 2017-11-27 15:16
I tried...but failed.
I dont know java.
Can you please make a PR with correct code for SongsCollection.java???

**Comment by cinder92** [comment] 2017-11-27 15:28
Sorry for maximum delay i will work into this issues, asap

**Comment by Madhukanth** [comment] 2017-11-27 15:35
Thank you...
Please look into it..

**Comment by flarocca** [comment] 2017-11-27 15:41
@cinder92 I will help this week, there two issues to fix, one of them is the null image and the other one, is to catch everything inside the loop, since one error should not prevent the rest to finalize successfully.

There is also a **Nice to have** related to how files are retrieved. I had am edge case with over 40 GB, and this process gets extremely slow and freezes the app. So we might want to add some batching mechanism. In other words, return in batches of N files until the end.

**Comment by Madhukanth** [comment] 2017-11-27 15:46
I can understand.
But don't know how to do it.
I will just wait for the solution.

Thank you for your reply.

**Comment by flarocca** [comment] 2017-11-28 13:07
@Madhukanth, I've created a new PR with some changes, but you can't update the package until it is merged and published. But you can copy/paste the code and test it. There are two files you need to copy:

- [module.js](https://github.com/cinder92/react-native-get-music-files/blob/master/module.js)
- [SongsCollection.java](https://github.com/cinder92/react-native-get-music-files/blob/master/android/src/main/java/com/dantecervantes/react/SongsCollection.java)

Let us know how it works.
Thanks.

**Comment by Madhukanth** [comment] 2017-11-28 13:13
Thank you so much.
I will use these files to process.

Again thank you for your kind work.

**Comment by Madhukanth** [comment] 2017-11-28 16:21
Sorry...The same repeats again.


java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference

**Comment by flarocca** [comment] 2017-11-28 16:29
where did you get the code? Take it from the new PR I've created.
https://github.com/cinder92/react-native-get-music-files/pull/13

**Comment by Madhukanth** [comment] 2017-11-28 16:59
Yes...I used your files to change the existing code.
I changed the Songs collection.java and module.js with your PR.

But the same error repeats..

**Comment by Madhukanth** [comment] 2017-11-28 17:09
But it has done  something..it collected all the cover images and it's blur images to the sdcard..The list is present in the sdcard..

**Comment by cinder92** [comment] 2017-11-29 06:28
Fixed in V2

**Closed as completed by cinder92** 2017-11-29 06:28 UTC
