### ISSUE TITLE
Gernerting signed apk build error 

### ISSUE THREAD

**Issue by muhammadashfaq** [cinder92/react-native-get-music-files#50] opened 2019-05-04 16:15 UTC
```
Execution failed for task ':react-native-get-music-files:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:7: error: resource android:attr/colorError not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:11: error: resource android:attr/colorError not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values-v26\values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values-v28\values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values\values.xml:2711: error: resource android:attr/fontStyle not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values\values.xml:2712: error: resource android:attr/font not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values\values.xml:2713: error: resource android:attr/fontWeight not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values\values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  C:\Users\HD\Documents\ReactNative\Nuuruliman\node_modules\react-native-get-music-files\android\build\intermediates\res\merged\release\values\values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.
```

**Comment by Drazail** [comment] 2019-05-04 23:04
@muhammadashfaq 
please provide more information.
Is your app running in development environment? which version are you using? are you installing via github or npm?

Also please reproduce the issue if possible.

**Comment by muhammadashfaq** [comment] 2019-05-05 07:58
react-native-cli: 2.0.1
react-native: 0.59.4


using npm 6.4.1

**Comment by Drazail** [comment] 2019-05-05 10:18
@muhammadashfaq

Does your app work in development environment?

I was not able to reproduce this issue, please reproduce it so we can take a closer look.

**Comment by muhammadashfaq** [comment] 2019-05-05 10:19
yes app is in development process.     I've uninstalled it from project and then apk generated successfully .

**Comment by Drazail** [comment] 2019-05-05 16:16
@muhammadshafaq

Please reproduce the issue in a public repo.

**Comment by muhammadashfaq** [comment] 2019-05-05 16:33
Sorry to say  i don't know how to reproduce issue in public repo.  can you tell me how to do it

**Comment by Drazail** [comment] 2019-05-05 19:08
@muhammadashfaq
Create a new app, add this module to the app, test it if it still doesn't work, if that was the case, push it to a public GitHub repo then share the link to that repo here. 🙂

**Comment by BlunT76** [comment] 2019-05-16 10:12
Hi
Same problem here, work in dev mode, but fail to compile
react-native-cli: 2.0.1
react-native: 0.59.8
npm: 6.9.0

android ./gradlew assembleRelease

> Configure project :react-native-get-music-files
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (27.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.3.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '27.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:bundleReleaseJsAndAssets
warning: the transform cache was reset.
Loading dependency graph, done.
info Writing bundle output to:, /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/android/app/build/generated/assets/react/release/index.android.bundle
info Done writing bundle output
info Copying 4 asset files
info Done copying assets

> Task :react-native-get-music-files:verifyReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-get-music-files:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:7: error: resource android:attr/colorError not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:11: error: resource android:attr/colorError not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: style attribute 'android:attr/keyboardNavigationCluster' not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:7: error: resource android:attr/dialogCornerRadius not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values-v28/values-v28.xml:11: error: resource android:attr/dialogCornerRadius not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values/values.xml:2711: error: resource android:attr/fontStyle not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values/values.xml:2712: error: resource android:attr/font not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values/values.xml:2713: error: resource android:attr/fontWeight not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values/values.xml:2714: error: resource android:attr/fontVariationSettings not found.
  /home/philippe/PROJETS/RN_0.59/MinimalCarDashboard/node_modules/react-native-get-music-files/android/build/intermediates/res/merged/release/values/values.xml:2715: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by Drazail** [comment] 2019-05-16 19:21
@BlunT76 

Are you installing this module via npm?
( Please note that RNAndroidAudioStore is not implemented in the npm version so if you are installing via npm you shouldn't register this class)

This is one of those issues that is really hard to figure out without access to the source code.

As I couldn't reproduce this issue, please help by either sharing your code or reproducing the issue.

**Comment by BlunT76** [comment] 2019-05-16 19:52
@Drazail 
I first installed via npm, re installed via npm install https://github.com/cinder92/react-native-get-music-files.git --save
Same result...

Here is my code: https://github.com/BlunT76/cardash

**Comment by Drazail** [comment] 2019-05-16 23:34
@BlunT76 
it seems to be working as intended.
I could generate an apk and run the app on both emulators and real devices. you can find the full project on the pull request I made into the master branch of your [repo](https://github.com/BlunT76/cardash/pull/1).

the issue is most probably related to `build.gradle` files, check those in the android project of the pull request.

**Comment by BlunT76** [comment] 2019-05-17 09:57
@Drazail 
Thanks for the pull request, i merged it, pull, but always same problem.
As you said, problem come from gradle, but i don't know how to solve it...
What version of gradle do you use?

SOLVED!!
I added this code a the end of /android/build-gradle
`subprojects {
        afterEvaluate {
            project ->
                if (project.hasProperty("android")) {
                    android {
                        compileSdkVersion = 28
                        buildToolsVersion = "28.0.3"
                    }
                }
        }
    }`

**Comment by Drazail** [comment] 2019-05-17 10:56
@BlunT76 

Android studio should have prompted you to update `compileSdkVersion` and `buildToolsVersion` to 28 if your project uses resources added in API level 28. Android studio can be weird like that at times .

unfortunately due to legacy support these parts of the modules should usually be updated manually according to the project's needs.

**Comment by BlunT76** [comment] 2019-05-17 12:13
@Drazail 
Yes, probably related as i updated android studio today, and installed many sdk

**Closed as completed** 2019-11-18 19:44 UTC

**Comment by shubhamdeol** [comment] 2020-05-30 09:18
@BlunT76 @Drazail   what was the issue exactly? I am also having the same error. 
Please document clearly how can I fix this. I do not get this error when I build from android studio.

**Comment by Drazail** [comment] 2020-06-05 08:35
@shubhamdeol 

Bump `compileSdkVersion` and `buildToolsVersion` to the latest.
